config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :tracks, only: [:index, :show] do
        member do
          post 'result'
        end
      end
      get 'tracks/search/:info_tag', to: 'tracks#search', as: 'search'
    end
  end
  resources :events do
    resources :tracks do
      resources :control_points, shallow: true, only: [:create, :destroy]
      member do
        post 'sort'
      end
      resources :results, only: [:index, :destroy], shallow: true
    end
  end

  get 'results/', to: 'results#events'
  get 'results/:event_id', to: 'results#event'
  get 'results/:event_id/:track_id/overall', to: 'results#overall', :as => :overall
  get 'results/:event_id/:track_id/splits', to: 'results#splits', :as => :splits

  root to: 'visitors#index'

  devise_for :users
  resources :users
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :event
  has_many :results, dependent: :destroy
  has_many :control_points, dependent: :destroy

  accepts_nested_attributes_for :control_points, allow_destroy: true,
    reject_if: proc { |attributes| attributes['tag_id'].blank? }

  has_attached_file :image, styles: { thumb: "60x60>" },
    default_url: "/images/:style/missing.png"
  validates_attachment :image, size: { in: 0..10.megabytes },
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"]}

  validates :name, :distance, :info_tag, presence: true
end

app/controllers/api/v1/tracks_controller.rb
class Api::V1::TracksController < Api::BaseController
  def index
    @tracks = Track.all
  end

  def show
    @track = Track.find(params[:id])
  end

  def search
    @track = Track.where(info_tag: params[:info_tag]).first
    if @track
      render :show
    else
      render json: { error: "Unknown info tag" }, status: 422
    end
  end

  def result
    track = Track.find(params[:id])
    @result = track.results.new(results_params)
    @result.control_points = params[:control_points]
    if @result.save
      head 201
    else
      render json: { error: @result.errors }, status: 422
    end
  end

  private
  def results_params
    params.permit(:nickname, :total_time, :complete)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :authenticate_user!
  before_action :set_track, only: [:show, :edit, :update, :destroy, :sort]

  def index
    @event = Event.find(params[:event_id])
    @tracks = @event.tracks.all
  end

  def show
  end

  def new
    @event = Event.find(params[:event_id])
    @track = @event.tracks.build
    3.times { @track.control_points.build }
  end

  def edit
    @track.control_points.build
  end

  def create
    @event = Event.find(params[:event_id])
    @track = @event.tracks.new(track_params)
    if @track.save
      redirect_to event_tracks_url(@event), notice: 'Track was successfully created.'
    else
      render :new
    end
  end

  def update
    if @track.update(track_params)
      redirect_to event_tracks_url(@event), notice: 'Track was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @track.destroy
    redirect_to event_tracks_url(@event), notice: 'Track was successfully destroyed.'
  end


  def sort
    params[:control_point].each_with_index do |id, index|
      control_point = @track.control_points.find(id)
      control_point.update_attribute(:position, index) if control_point
    end
    render nothing: true
  end


  private
    def set_track
      @event = Event.find(params[:event_id])
      @track = Track.find(params[:id])
    end

    def track_params
      params.require(:track).permit(:distance, :name, :image, :info_tag, control_points_attributes: [:id, :tag_id])
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.slim
= simple_form_for([@event, @track], html: { multipart: true } ) do |f|
  = f.error_notification

  .form-inputs
    = f.input :distance
    = f.input :name
    = f.input :info_tag
    = f.file_field :image

  h4 Add Tag ID
  #nested-control-points
    = f.simple_fields_for :control_points do |control_point_form|
      .nested_control_points_form
        = control_point_form.input :tag_id, label: "NFC Tag ID"

        - if control_point_form.object.new_record?
          = link_to 'Remove', '', remote: true, class: 'remove_control_point'
        - else
          = link_to 'Remove', control_point_path(control_point_form.object), method: :delete, remote: true, class: 'remove_control_point'
          = control_point_form.input :id, as: :hidden
    = link_to 'Add Another NFC Tag', '#', class: 'add_control_point'

  .form-actions
    = f.button :submit

app/views/tracks/edit.html.slim
h1 Editing track

== render 'form'

= link_to "#{@event.name}", event_tracks_path(@event)
= link_to 'Events', events_path

app/views/tracks/index.html.slim
h1 Listing tracks of #{ @event.name }

table
  thead
    tr
      th Name
      th Distance
      th Image
      th
      th
      th

  tbody
    - @tracks.each do |track|
      tr
        td = track.name
        td = track.distance
        td = image_tag track.image.url(:thumb)
        td = link_to 'Results', event_track_results_path(@event, track)
        td = link_to 'Show', event_track_path(@event, track)
        td = link_to 'Edit', edit_event_track_path(@event, track)
        td = link_to 'Destroy', event_track_path(@event, track), data: {:confirm => 'Are you sure?'}, :method => :delete
br
= link_to 'New Track', new_event_track_path(@event)

app/views/tracks/new.html.slim
h1 New track

== render 'form'

= link_to 'Back', event_tracks_path(@event)

app/views/tracks/show.html.slim
p#notice = notice

h1 Track of #{ @event.name }

p
  strong Name:
  = @track.name
p
  strong Distance:
  = @track.distance
p
  strong Image:
  = image_tag @track.image

div
  h4 Available Control Points:
  ul.control-points data-update-url="#{ sort_event_track_path(@event, @track)}"
    - @track.control_points.each do |cp|
      = content_tag_for(:li, cp)
        span = cp.tag_id


= link_to 'Edit', edit_event_track_path(@event, @track)
'|
= link_to 'Back', event_tracks_path(@event)