config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :tracks, only: [:index, :show] do
        member do
          post 'result'
        end
      end
      get 'tracks/search/:info_tag', to: 'tracks#search', as: 'search'
    end
  end
  resources :events do
    resources :tracks do
      resources :control_points, shallow: true, only: [:create, :destroy]
      member do
        post 'sort'
      end
      resources :results, only: [:index, :destroy], shallow: true
    end
  end

  get 'results/', to: 'results#events'
  get 'results/:event_id', to: 'results#event'
  get 'results/:event_id/:track_id/overall', to: 'results#overall', :as => :overall
  get 'results/:event_id/:track_id/splits', to: 'results#splits', :as => :splits

  root to: 'visitors#index'

  devise_for :users
  resources :users
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :track
  serialize :control_points, Array
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  before_action :authenticate_user!, :except => [:events, :event, :overall, :splits]

  def index
    @track = Track.find(params[:track_id])
    @results = @track.results.all
  end

  def destroy
    @result = Result.find(params[:id])
    @result.destroy
    redirect_to event_track_results_path(@result.track.event, @result.track), notice: 'Result was successfully destroyed.'
  end

  def events
    @events = Event.all
  end

  def event
    @event = Event.find(params[:event_id])
    @tracks = @event.tracks.all
  end

  def overall
    @event = Event.find(params[:event_id])
    @track = Track.find(params[:track_id])
    @results = @track.results.all.sort_by { |r| r.total_time.to_i }
  end

  def splits
    @event = Event.find(params[:event_id])
    @track = Track.find(params[:track_id])
    @control_points = @track.control_points.all
    first, *@control_points = @control_points # drops first tag (the starting tag)
    @results = @track.results.all.sort_by { |r| r.total_time.to_i }
  end

end

app/views/results/event.html.slim
h1 Tracks of #{@event.name}

table.tracks
  thead
    tr
      th Name
      th Distance
      th Results
      th Split times

  tbody
    - @tracks.each do |t|
      tr
        td = t.name
        td = t.distance
        td = link_to 'Overall results', overall_path(@event, t)
        td = link_to 'Split times', splits_path(@event, t)

= link_to 'Other events\' results', results_path

app/views/results/events.html.slim
h1 Results of events

table.events
  thead
    tr
      th Name
      th Location
      th Start date
      th End date
      th Address
      th Results

  tbody
    - @events.each do |event|
      tr
        td = event.name
        td = event.location
        td = event.start_date.strftime("%e.%-m.%y %R")
        td = event.end_date.strftime("%e.%-m.%y %R")
        td = event.starting_point
        td = link_to 'Results', result_path(event)

app/views/results/index.html.slim
h1 Results
table
  thead
    tr
      th S. No.
      th Nick Name
      th Total Time
      th Completed
      th

  tbody
    - @results.each_with_index do |result, index|
      tr
        td = index+1
        td = result.nickname
        td = result.total_time
        td = result.complete ? "Complete": "Incomplete"
        td = link_to 'Delete', result_path(result), data: {confirm: 'Are you sure?'}, method: :delete

br
= link_to 'Back to Tracks', event_tracks_path(@track.event)

app/views/results/overall.html.slim
h1 Overall results for track #{@track.name} in event #{@event.name}

table
  thead
    tr
      th #
      th Nick Name
      th Total Time
      th Completed
      th Uploaded

  tbody
    - @results.each_with_index do |result, index|
      tr
        td = index+1
        td = result.nickname
        td = result.total_time ? (Time.new(0) + (result.total_time.to_i / 1000).seconds).strftime("%T") : "-"
        td = result.complete ? "Complete": "Incomplete"
        td = result.created_at ? result.created_at.strftime("%e.%-m.%y %R") : "-"

br
= link_to 'Back to other tracks', result_path(@track.event)

app/views/results/splits.html.slim
h1 Split time results for track #{@track.name} in event #{@event.name}

table
  thead
    tr
      th #
      th Nick Name
      - @control_points.each_with_index do |cp, index|
        th = (index + 1).to_s + "-" + cp.tag_id
      th Total time
      th Uploaded

  tbody
    - @results.each_with_index do |result, index|
      tr
        td = index+1
        td = result.nickname
        - @control_points.each_with_index do |cp, index|
          - time = result.control_points.select {|c| c[:tag_id].to_s == cp.tag_id.to_s}
          - time = time.empty? ? 0 : time.first[:time]
          td = time && time != 0 ? (Time.new(0) + (time.to_i.round(-3) / 1000).seconds).strftime("%T") : "-"
        td = result.total_time ? (Time.new(0) + (result.total_time.to_i.round(-3) / 1000).seconds).strftime("%T") : "-"
        td = result.created_at ? Time.parse(result.created_at.to_s).strftime("%e.%-m.%y %R") : "-"
br
= link_to 'Back to other tracks', result_path(@track.event)