config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :tracks, only: [:index, :show] do
        member do
          post 'result'
        end
      end
      get 'tracks/search/:info_tag', to: 'tracks#search', as: 'search'
    end
  end
  resources :events do
    resources :tracks do
      resources :control_points, shallow: true, only: [:create, :destroy]
      member do
        post 'sort'
      end
      resources :results, only: [:index, :destroy], shallow: true
    end
  end

  get 'results/', to: 'results#events'
  get 'results/:event_id', to: 'results#event'
  get 'results/:event_id/:track_id/overall', to: 'results#overall', :as => :overall
  get 'results/:event_id/:track_id/splits', to: 'results#splits', :as => :splits

  root to: 'visitors#index'

  devise_for :users
  resources :users
end

app/models/event.rb
class Event < ActiveRecord::Base

  has_many :tracks, dependent: :destroy
  validates :name, :location, :start_date, :end_date, :starting_point, presence: true

  scope :active, -> { where("? BETWEEN start_date AND end_date", Date.today) }

  def active?
    self.start_date < Time.now and self.end_date > Time.now
  end

end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::BaseController

  def index
    @events = Event.all
    # render json: @events.to_json
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :location, :start_date, :end_date, :starting_point)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.slim
= simple_form_for(@event) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :location
    = f.input :start_date
    = f.input :end_date
    = f.input :starting_point

  .form-actions
    = f.button :submit

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

= link_to 'Show', @event
'|
= link_to 'Back', events_path

app/views/events/index.html.slim
h1 Listing events

table#events
  thead
    tr
      th Name
      th Location
      th Start date
      th End date
      th Starting point
      th
      th
      th

  tbody
    - @events.each do |event|
      tr
        td = link_to event.name, event_path(event)
        td = event.location
        td = event.start_date
        td = event.end_date
        td = event.starting_point
        td = link_to 'Tracks', event_tracks_path(event) if user_signed_in?
        td = link_to 'Edit', edit_event_path(event) if user_signed_in?
        td = link_to 'Destroy', event, data: {:confirm => 'Are you sure?'}, :method => :delete if user_signed_in?

br

- if user_signed_in?
  = link_to 'New Event', new_event_path

app/views/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', events_path

app/views/events/show.html.slim
p#notice = notice

p
  strong Name:
  = @event.name
p
  strong Location:
  = @event.location
p
  strong Start date:
  = @event.start_date
p
  strong End date:
  = @event.end_date
p
  strong Starting point:
  = @event.starting_point

= link_to 'Edit', edit_event_path(@event)
'|
= link_to 'Back', events_path