config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :tracks, only: [:index, :show] do
        member do
          post 'result'
        end
      end
      get 'tracks/search/:info_tag', to: 'tracks#search', as: 'search'
    end
  end
  resources :events do
    resources :tracks do
      resources :control_points, shallow: true, only: [:create, :destroy]
      member do
        post 'sort'
      end
      resources :results, only: [:index, :destroy], shallow: true
    end
  end

  get 'results/', to: 'results#events'
  get 'results/:event_id', to: 'results#event'
  get 'results/:event_id/:track_id/overall', to: 'results#overall', :as => :overall
  get 'results/:event_id/:track_id/splits', to: 'results#splits', :as => :splits

  root to: 'visitors#index'

  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div[class="alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert]
      = content_tag :div, msg
      a.close[href="#"]
        | ×

app/views/layouts/_navigation.html.slim
/ navigation styled for Zurb Foundation 5
nav.top-bar[data-topbar]
  ul.title-area
    li.name
      = link_to 'Home', root_path
    li.toggle-topbar.menu-icon
      a[href="#"]
        Menu
  .top-bar-section
    ul
      == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  li
    = link_to 'Events', events_path
  li
    = link_to 'Users', users_path
  li
    =link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  li
    = link_to 'Sign in', new_user_session_path
li
  = link_to 'Results', results_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Orienteering'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Orienteering'}"
    == stylesheet_link_tag "application", :media => 'all'
    / Modernizr is required for Zurb Foundation
    == javascript_include_tag 'vendor/modernizr'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body.twelve-columns
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield